// Merge workflow research (enriched.json) with structured-address geocoding
// (addr-geocoded.json) into the app dataset src/data/places.js.
// Coordinate priority: structured address geocode (most accurate for a street
// address) → workflow's address-derived coord. Disagreements are logged.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const enriched = JSON.parse(readFileSync(new URL('./enriched.json', import.meta.url)));
let addr = [];
try {
  addr = JSON.parse(readFileSync(new URL('./addr-geocoded.json', import.meta.url)));
} catch {
  console.warn('No addr-geocoded.json — using workflow coords only.');
}
const addrByName = new Map(addr.map((a) => [a.name, a]));

const OKC = { latMin: 35.20, latMax: 35.80, lonMin: -97.85, lonMax: -97.20 };
const inOKC = (lat, lng) => lat >= OKC.latMin && lat <= OKC.latMax && lng >= OKC.lonMin && lng <= OKC.lonMax;

const R = 3958.8;
const toRad = (d) => (d * Math.PI) / 180;
const miBetween = (a, b) => {
  const dLat = toRad(b.lat - a.lat), dLng = toRad(b.lng - a.lng);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
};

const cleanName = (n) => n.replace(/\s*\(.*?\)\s*$/, '').trim();

const usedIds = new Set();
const slug = (name) => {
  let base = name.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  let id = base, i = 2;
  while (usedIds.has(id)) id = `${base}-${i++}`;
  usedIds.add(id);
  return id;
};

const records = [];
const warnings = [];
for (const p of enriched) {
  const a = addrByName.get(p.name);
  const wf = inOKC(p.lat, p.lng) ? { lat: p.lat, lng: p.lng } : null;
  const ag = a && a.addrLat != null && inOKC(a.addrLat, a.addrLng) ? { lat: a.addrLat, lng: a.addrLng } : null;

  let coord, source;
  if (ag) { coord = ag; source = 'address-geocode'; }
  else if (wf) { coord = wf; source = 'workflow'; }
  else { coord = { lat: p.lat, lng: p.lng }; source = 'workflow-unverified'; warnings.push(`${p.name}: no in-bounds coord, using raw ${p.lat},${p.lng}`); }

  if (ag && wf) {
    const d = miBetween(ag, wf);
    if (d > 0.6) warnings.push(`${p.name}: address-geocode vs workflow disagree by ${d.toFixed(2)} mi (using address-geocode)`);
  }

  records.push({
    id: slug(cleanName(p.name)),
    name: cleanName(p.name),
    category: p.category,
    district: p.district || 'Other',
    address: p.address || '',
    lat: +coord.lat.toFixed(6),
    lng: +coord.lng.toFixed(6),
    vibe: p.vibe || '',
    priceTier: p.priceTier || '',
    caveat: p.caveat || '',
    source,
  });
}

records.sort((x, y) => x.district.localeCompare(y.district) || x.name.localeCompare(y.name));

const header = `// AUTO-GENERATED by tools/build-data.mjs — do not hand-edit.
// Source: coworker's list -> web-research verification -> OpenStreetMap geocoding.
// ${records.length} places. To regenerate: node tools/build-data.mjs
`;
const body = `export const PLACES = ${JSON.stringify(records, null, 2)};\n`;

mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true });
writeFileSync(new URL('../src/data/places.js', import.meta.url), header + '\n' + body);

console.log(`Wrote src/data/places.js with ${records.length} places.`);
const bySrc = records.reduce((m, r) => ((m[r.source] = (m[r.source] || 0) + 1), m), {});
console.log('Coord sources:', bySrc);
if (warnings.length) {
  console.log(`\n${warnings.length} note(s):`);
  warnings.forEach((w) => console.log('  - ' + w));
}
